<a href="https://colab.research.google.com/github/YounSooKimTech/Joy_Criminology/blob/main/ACS_200_2004_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DD

- https://www2.census.gov/acs/downloads/Core_Tables/

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Profiles0402000.csv")

df_temp = df[ ((df["Table Number"] == 1) & (df["Order"].isin([1.0, 2, 17, 25]))) |
    ((df["Table Number"] == 2) & (df["Order"] == 16)) |
    ((df["Table Number"] == 3) & (df["Order"].isin([6, 89]))) ]

df_temp = df_temp.drop(["Geographic ID Code", "Table Number", "Order", "Lower Bound", "Upper Bound"], axis=1)

df_temp_long = df_temp.pivot(index='Geographic Name', columns='Stub', values='Estimate').reset_index()
df_temp_long.columns = df_temp_long.columns.str.replace('\n', '').str.replace('[()]', '', regex=True)
df_temp_long.columns = df_temp_long.columns.str.replace("bachelor's degree", "BA")
df_temp_long

df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].replace("," , "", regex=True)
df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')


df_temp_long["Year"] = 2000
df_temp_long["Percent Male"] = round(df_temp_long["Male"]/df_temp_long["Total population"] * 100, 2)
df_temp_long["Percent White"] = round(df_temp_long["White"]/df_temp_long["Total population"] * 100, 2)

df_2000 = df_temp_long[["Geographic Name", "Year", "Median age years", "Percent Male", "Percent White",
              "Percent BA or higher", "Percent unemployed", "Per capita income dollars" ]]

#df_2000

<ipython-input-285-db1f8892b567>:15: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

In [ ]:
df = pd.read_csv("/content/Profiles0402001.csv")

df_temp = df[( (df["Table"] == 1) & df["Subtable"].isin([1.0, 2, 17, 25]) |
    (df["Table"] == 2) & (df["Subtable"] == 16) |
    (df["Table"] == 3) & df["Subtable"].isin([6, 91]) )]

df_temp = df_temp.drop(["Table", "Subtable", "Unnamed: 5","Unnamed: 6"], axis=1)

df_temp_long = df_temp.pivot(index='Geographic Name', columns='Stub', values='Estimate').reset_index()

df_temp_long.columns = df_temp_long.columns.str.replace('\n', '').str.replace('[()]', '', regex=True)
df_temp_long.columns = df_temp_long.columns.str.replace("bachelor's degree", "BA")

df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].replace("," , "", regex=True)
df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

df_temp_long["Year"] = 2001
df_temp_long["Percent Male"] = round(df_temp_long["Male"]/df_temp_long["Total population"] * 100, 2)
df_temp_long["Percent White"] = round(df_temp_long["White"]/df_temp_long["Total population"] * 100, 2)


df_2001 = df_temp_long[["Geographic Name", "Year", "Median age years", "Percent Male", "Percent White",
              "Percent BA or higher", "Percent unemployed", "Per capita income dollars" ]]
#df_2001

<ipython-input-286-f0243c8277a1>:15: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

In [ ]:
df = pd.read_csv("/content/Profiles0402002.csv")
df_temp = df [(df["Table"]==1) & df["Table Order"].isin([2, 4, 20, 31]) |
    (df["Table"] == 2) & (df["Table Order"] == 21) |
    (df["Table"] == 3) & df["Table Order"].isin([8, 111]) ]

df_temp = df_temp[["Geographic Name", "Stub", "Estimate"]]


df_temp_long = df_temp.pivot(index='Geographic Name', columns='Stub', values='Estimate').reset_index()
df_temp_long.columns = df_temp_long.columns.str.replace('\n', '').str.replace('[()]', '', regex=True)
df_temp_long.columns = df_temp_long.columns.str.replace("bachelor's degree", "BA")

df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

df_temp_long["Year"] = 2002
df_temp_long["Percent Male"] = round(df_temp_long["Male"]/df_temp_long["Total population"] * 100, 2)
df_temp_long["Percent White"] = round(df_temp_long["White"]/df_temp_long["Total population"] * 100, 2)

df_2002 = df_temp_long[["Geographic Name", "Year", "Median age years", "Percent Male", "Percent White",
              "Percent BA or higher", "Percent unemployed", "Per capita income dollars" ]]
#df_2002

<ipython-input-287-3b7fb248c986>:13: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

In [ ]:
df = pd.read_csv("/content/Profiles0402003.csv")


df[(df["Table Number"] == 1) & (df["Table Order"].isin([2, 4, 20, 31]))]
df[(df["Table Number"] == 2) & (df["Table Order"] == 21)]
df[(df["Table Number"] == 3) & (df["Table Order"].isin([8, 109]))]

df_temp = df [ (df["Table Number"] == 1) & (df["Table Order"].isin([2, 4, 20, 31])) |
     (df["Table Number"] == 2) & (df["Table Order"] == 21) |
    (df["Table Number"] == 3) & df["Table Order"].isin([8, 109]) ]


df_temp = df_temp[["Geographic Name", "Stub", "Estimate"]]

df_temp_long = df_temp.pivot(index='Geographic Name', columns='Stub', values='Estimate').reset_index()
df_temp_long.columns = df_temp_long.columns.str.replace('\n', '').str.replace('[()]', '', regex=True)
df_temp_long.columns = df_temp_long.columns.str.replace("bachelor's degree", "BA")

df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

df_temp_long["Year"] = 2003
df_temp_long["Percent Male"] = round(df_temp_long["Male"]/df_temp_long["Total population"] * 100, 2)
df_temp_long["Percent White"] = round(df_temp_long["White"]/df_temp_long["Total population"] * 100, 2)

df_2003 = df_temp_long[["Geographic Name", "Year", "Median age years", "Percent Male", "Percent White",
              "Percent BA or higher", "Percent unemployed", "Per capita income dollars" ]]

<ipython-input-288-34104f2b5cd3>:19: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

In [ ]:
df = pd.read_csv("/content/Profiles0402004.csv")

df[(df["Table Number"] == 1) & (df["Table Order"].isin([1, 3, 19, 40]))]
df[(df["Table Number"] == 2) & (df["Table Order"] == 20)]
df[(df["Table Number"] == 3) & (df["Table Order"].isin([11, 111]))]

df_temp = df [ (df["Table Number"] == 1) & (df["Table Order"].isin([1, 3, 19, 40])) |
     (df["Table Number"] == 2) & (df["Table Order"] == 20) |
    (df["Table Number"] == 3) & df["Table Order"].isin([11, 111]) ]

df_temp = df_temp[["Geographic Name", "Stub", "Estimate"]]

df_temp_long = df_temp.pivot(index='Geographic Name', columns='Stub', values='Estimate').reset_index()
df_temp_long.columns = df_temp_long.columns.str.replace('\n', '').str.replace('[()]', '', regex=True)
df_temp_long.columns = df_temp_long.columns.str.replace("bachelor's degree", "BA")

df_temp_long.iloc[:, 1:] = df_temp_long.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

df_temp_long["Year"] = 2004
df_temp_long["Percent Male"] = round(df_temp_long["Male"]/df_temp_long["Total population"] * 100, 2)
df_temp_long["Percent White"] = round(df_temp_long["White"]/df_temp_long["Total population"] * 100, 2)

df_temp_long.rename(columns={"Unemployed" : "Percent unemployed"}, inplace=True)


df_2004 = df_temp_long[["Geographic Name", "Year", "Median age years", "Percent Male", "Percent White",
              "Percent BA or higher", "Percent unemployed", "Per capita income dollars" ]]

# df_2004

<ipython-input-289-705935996d4a>:17: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

In [ ]:
df_2000.columns
df_2001.columns
df_2002.columns
df_2003.columns
df_2004.columns

df_0004 = pd.concat([df_2000, df_2001, df_2002, df_2003, df_2004], ignore_index=True)

df_0004["Year"].value_counts()

2000    51
2001    51
2002    51
2003    51
2004    51
Name: Year, dtype: int64

In [ ]:
df_0004.columns

Index(['Geographic Name', 'Year', 'Median age years', 'Percent Male',
       'Percent White', 'Percent BA or higher', 'Percent unemployed',
       'Per capita income dollars'],
      dtype='object', name='Stub')

In [ ]:
! pip install us
import us

def state_name_to_abbreviation(state_name):
    state = us.states.lookup(state_name)
    if state:
        return state.abbr
    else:
        return state_name

df_0004['State'] = df_0004["Geographic Name"].apply(state_name_to_abbreviation)

df_0004["State"] = df_0004["State"].str.replace("District of Columbia", "DC")

Requirement already satisfied: us in /usr/local/lib/python3.10/dist-packages (3.1.1)
Requirement already satisfied: jellyfish==0.11.2 in /usr/local/lib/python3.10/dist-packages (from us) (0.11.2)

In [ ]:
new_col_order = [df_0004.columns.tolist()[-1]] + df_0004.columns.tolist()[0:]

df_0004 = df_0004[new_col_order]
df_0004 = df_0004.iloc[:, :-1]
df_0004

Stub,State,Geographic Name,Year,Median age years,Percent Male,Percent White,Percent BA or higher,Percent unemployed,Per capita income dollars
0,AL,Alabama,2000,36.0,47.90,71.65,20.0,6.4,40778
1,AK,Alaska,2000,32.6,51.14,70.65,26.0,7.8,59060
2,AZ,Arizona,2000,34.3,49.50,78.67,22.5,6.3,45840
3,AR,Arkansas,2000,36.3,48.51,80.05,16.7,6.4,39592
4,CA,California,2000,33.3,49.46,67.87,27.5,6.1,53096
...,...,...,...,...,...,...,...,...,...
250,VA,Virginia,2004,36.9,48.82,72.65,32.7,5.5,27820
251,WA,Washington,2004,36.4,49.57,80.97,31.3,8.3,25212
252,WV,West Virginia,2004,40.3,48.79,95.03,16.3,6.8,18025
253,WI,Wisconsin,2004,37.5,49.44,88.10,24.1,6.9,23350
254,WY,Wyoming,2004,38.4,50.10,92.50,24.8,4.8,24036

In [ ]:
df_0004

Stub,State,Geographic Name,Year,Median age years,Percent Male,Percent White,Percent BA or higher,Percent unemployed,Per capita income dollars
0,AL,Alabama,2000,36.0,47.90,71.65,20.0,6.4,40778
1,AK,Alaska,2000,32.6,51.14,70.65,26.0,7.8,59060
2,AZ,Arizona,2000,34.3,49.50,78.67,22.5,6.3,45840
3,AR,Arkansas,2000,36.3,48.51,80.05,16.7,6.4,39592
4,CA,California,2000,33.3,49.46,67.87,27.5,6.1,53096
...,...,...,...,...,...,...,...,...,...
250,VA,Virginia,2004,36.9,48.82,72.65,32.7,5.5,27820
251,WA,Washington,2004,36.4,49.57,80.97,31.3,8.3,25212
252,WV,West Virginia,2004,40.3,48.79,95.03,16.3,6.8,18025
253,WI,Wisconsin,2004,37.5,49.44,88.10,24.1,6.9,23350
254,WY,Wyoming,2004,38.4,50.10,92.50,24.8,4.8,24036

In [ ]:
import pandas as pd

df_0004.to_csv("ACS_2000_2004.csv", index=False)

In [ ]:
df_0004["State"].value_counts()

AL    5
PA    5
NV    5
NH    5
NJ    5
NM    5
NY    5
NC    5
ND    5
OH    5
OK    5
OR    5
RI    5
MT    5
SC    5
SD    5
TN    5
TX    5
UT    5
VT    5
VA    5
WA    5
WV    5
WI    5
NE    5
MO    5
AK    5
ID    5
AZ    5
AR    5
CA    5
CO    5
CT    5
DE    5
DC    5
FL    5
GA    5
HI    5
IL    5
MS    5
IN    5
IA    5
KS    5
KY    5
LA    5
ME    5
MD    5
MA    5
MI    5
MN    5
WY    5
Name: State, dtype: int64

# Check the dataset

In [ ]:
! pip install plotly
! pip install -U kaleido

In [ ]:
! pip install plotly
! pip install kaleido

Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (23.2)
Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 10.1 MB/s eta 0:00:00
Installing collected packages: kaleido
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
Successfully installed kaleido-0.2.1

In [ ]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/YounSooKimTech/Joy_Criminology/main/Data/ACS_2000_2004.csv")

In [ ]:
df.columns

Index(['State', 'Geographic Name', 'Year', 'Median age years', 'Percent Male',
       'Percent White', 'Percent BA or higher', 'Percent unemployed',
       'Per capita income dollars'],
      dtype='object')

In [ ]:
df.groupby("State")["Percent BA or higher"].mean().sort_values(ascending=False)

State
DC    43.54
MA    35.86
CO    33.72
CT    33.64
MD    33.34
NJ    31.96
VA    31.60
VT    30.60
NH    30.38
WA    30.02
MN    29.22
NY    29.10
CA    28.54
IL    27.98
HI    27.86
KS    27.50
RI    27.34
AK    26.72
UT    26.68
OR    26.22
DE    26.20
MT    25.68
NE    25.30
GA    24.68
TX    24.46
FL    24.32
ME    24.26
NM    24.26
WY    23.90
ND    23.80
MI    23.72
PA    23.68
MO    23.64
AZ    23.60
SD    23.42
NC    23.42
WI    23.38
SC    23.30
ID    22.74
IA    22.66
OH    22.08
TN    21.18
OK    21.08
IN    20.64
AL    20.62
LA    20.34
NV    18.86
MS    18.56
KY    18.32
AR    18.30
WV    15.82
Name: Percent BA or higher, dtype: float64

In [ ]:
import plotly.express as px
import kaleido

fig = px.choropleth(df,
                    locations="State",
                    locationmode='USA-states',
                    color="Percent BA or higher",
                    range_color = [10, 35],
                    color_continuous_scale="Jet",
                    scope='usa',
                    animation_frame='Year',
                    title = "Time Trend of Median Age")

fig.write_html("Education above BA.html")
fig.show()